CREATE TABLE LIBRARY_LOAN (
    LOAN_ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    STUDENT_INDEX INT NOT NULL,
    BOOK_TITLE NVARCHAR(100) NOT NULL,
    LOAN_DATE DATE NOT NULL,
    OVERDUE_FEE MONEY NOT NULL DEFAULT 0
)